version: '3.0'

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - './html:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  php:
    build:
      context: docker/php/
    volumes:
      - './html:/var/www/html'

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1


